export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const SWITCH_LOGGED_IN = 'SWITCH_LOGGED_IN';
export const UPDATE_TIPS = 'UPDATE_TIPS';
export const UPDATE_TOPICS = 'UPDATE_TOPICS';
export const RELOAD_TIPS = 'RELOAD_TIPS';
export const SET_TIPS_ORDERING = 'SET_TIPS_ORDERING';
