name: Production Web Pipeline

on:
  push:
    branches: 
      - master
    tags:
      - 'v*'

env:
  ENV: "prd"

jobs:
  main:
    runs-on: ubuntu-latest    
    name: Web build docker
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract metadata for docker
        if: |
          github.event_name == 'push' ||
          startsWith(github.ref, 'refs/tags/v')
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aeternity/superhero-ui-web
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=ref,event=tag
            type=ref,event=pr
      
      - name: Build and push docker image
        if: |
          github.event_name == 'push' ||
          startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Get the tag version
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_version
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Production Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        uses: aeternity/ae-github-actions/argocd-deploy@v1
        with:
          url-prefix: ${{ steps.get_version.outputs.TAG }}
          env: ${{ env.ENV }}

