name: Staging Deploy Pipeline

on:
  workflow_run:
    workflows: [ "WEB Pipeline", "SSR Pipeline" ]
    types:
      - completed

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: staging
          persist-credentials: false
          fetch-depth: 0
      
      - name: Modify values for staging deploy
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          sudo snap install yq
          export FULL_PR_NUMBER="pr-$PR_NUMBER"
          yq eval -i '.app.versions += [env(FULL_PR_NUMBER)'] superhero-ui/values-staging.yaml
          yq eval -i '.app.ingress.hosts += [{"host": "'${FULL_PR_NUMBER}'.stg.aepps.com", "paths": { "path": "/"}}]' superhero-ui/values-staging.yaml
          yq eval -i '.. style="double"' superhero-ui/values-staging.yaml
          cat superhero-ui/values-staging.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy ${FULL_PR_NUMBER}.stg.aepps.com"

      - name: Push deploy changes to staging branch
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: aeternity/gitops-apps
          branch: staging
