name: Staging Deploy Pipeline

on:
  pull_request:
    types: [ opened, closed ] 
    branches:
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - run: echo "pr-$PR_NUMBER" | tee -a $FULL_PR_NUMBER

      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: staging
          persist-credentials: false
          fetch-depth: 0
      
      - name: Modify values for staging deploy
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          sudo snap install yq
          yq eval -i '.app.versions += [env(FULL_PR_NUMBER)'] superhero-ui/values.yaml
          yq eval -i '.app.ingress.hosts += [{"host": "'${FULL_PR_NUMBER}'.dev.aepps.com", "paths": { "path": "/"}}]' superhero-ui/values.yaml
          yq eval -i '.. style="double"' superhero-ui/values.yaml
          cat superhero-ui/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy ${FULL_PR_NUMBER}.dev.aepps.com"

      - name: Push deploy changes to staging branch
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: aeternity/gitops-apps
          branch: staging

  undeploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: staging
          persist-credentials: false
          fetch-depth: 0

      - uses: rlespinasse/github-slug-action@v3.x
      
      - name: Modify values for staging deploy
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          sudo snap install yq
          yq eval -i 'del( .app.versions[] | select(. == env(FULL_PR_NUMBER))  )' superhero-ui/values.yaml
          yq eval -i 'del(... | select(.[] == "'${FULL_PR_NUMBER}.dev.aepps.com'"))' superhero-ui/values.yaml
          cat superhero-ui/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Undeploy ${FULL_PR_NUMBER}.dev.aepps.com"

      - name: Push deploy changes to staging branch
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: aeternity/gitops-apps
          branch: staging
  
  remove-dockerhub-tags-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Remove tags from dockerhub
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          login_data() {
          cat <<EOF
          {
            "username": "$DOCKERHUB_USER",
            "password": "$DOCKERHUB_PASS"
          }
          EOF
          }                                                    
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "$(login_data)" "https://hub.docker.com/v2/users/login/" | jq -r .token)
          curl "https://hub.docker.com/v2/repositories/aeternity/superhero-ui-web/tags/${FULL_PR_NUMBER}/" \
          -X DELETE \
          -H "Authorization: JWT ${TOKEN}"
