name: Staging Deploy Pipeline

on:
  workflow_run:
    workflows: ["Web Pipeline"]
    types:
      - completed

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    needs: web-docker
    steps:
      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: staging
          persist-credentials: false
          fetch-depth: 0

      - name: Modify values for staging deploy
        #if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          sudo snap install yq
          export FULL_PR_NUMBER="pr-$PR_NUMBER"
          yq eval -i '.app.versions += [env(FULL_PR_NUMBER)'] superhero-ui/values-staging.yaml
          yq eval -i '.app.ingress.hosts += [{"host": "'${FULL_PR_NUMBER}'.stg.aepps.com", "paths": { "path": "/"}}]' superhero-ui/values-staging.yaml
          yq eval -i '.. style="double"' superhero-ui/values-staging.yaml
          cat superhero-ui/values-staging.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy ${FULL_PR_NUMBER}.stg.aepps.com"

      - name: Push deploy changes to staging branch
        #if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: aeternity/gitops-apps
          branch: staging

  undeploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: staging
          persist-credentials: false
          fetch-depth: 0
      
      - name: Modify values for staging undeploy
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          sudo snap install yq
          export FULL_PR_NUMBER="pr-$PR_NUMBER"
          yq eval -i 'del( .app.versions[] | select(. == env(FULL_PR_NUMBER))  )' superhero-ui/values-staging.yaml
          yq eval -i 'del(... | select(.[] == "'${FULL_PR_NUMBER}.stg.aepps.com'"))' superhero-ui/values-staging.yaml
          cat superhero-ui/values-staging.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Undeploy ${FULL_PR_NUMBER}.stg.aepps.com"

      - name: Push undeploy changes to staging branch
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: aeternity/gitops-apps
          branch: staging
  
  remove-dockerhub-tags-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Remove tags from dockerhub
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          export FULL_PR_NUMBER="pr-$PR_NUMBER"
          echo "https://hub.docker.com/v2/repositories/aeternity/superhero-ui-web/tags/${FULL_PR_NUMBER}/"
          login_data() {
          cat <<EOF
          {
            "username": "$DOCKERHUB_USER",
            "password": "$DOCKERHUB_PASS"
          }
          EOF
          }

          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "$(login_data)" "https://hub.docker.com/v2/users/login/" | jq -r .token)
          echo "https://hub.docker.com/v2/repositories/aeternity/superhero-ui-web/tags/${FULL_PR_NUMBER}/"
          curl "https://hub.docker.com/v2/repositories/aeternity/superhero-ui-web/tags/${FULL_PR_NUMBER}/" \
          -X DELETE \
          -H "Authorization: JWT ${TOKEN}"
