name: Staging Deploy Test Pipeline

on:
  pull_request:
    types: [ opened, closed ]
    branches:
      - feat/gh-actions-docker-build

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: dev
          persist-credentials: false
          fetch-depth: 0

      - uses: rlespinasse/github-slug-action@v3.x
      
      - name: Modify values for staging deploy
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          sudo snap install yq
          yq eval -i '.app.versions += env(GITHUB_REF_SLUG)' superhero-ui/values.yaml
          yq eval -i '.app.ingress.hosts += [{"host": "'${GITHUB_REF_SLUG}'.dev.aepps.com", "paths": { "path": "/"}}]' superhero-ui/values.yaml
          yq eval -i '.. style="double"' superhero-ui/values.yaml
          cat superhero-ui/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy ${GITHUB_REF_SLUG}.dev.aepps.com"

      - name: Push deploy changes to staging branch
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: aeternity/gitops-apps
          branch: dev

  
  undeploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: dev
          fetch-depth: 0

      - uses: rlespinasse/github-slug-action@v3.x
      
      - name: Modify values for staging deploy
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          sudo snap install yq
          yq eval -i 'del(... | select(.[] == "'${GITHUB_REF_SLUG}.dev.aepps.com'"))' superhero-ui/values.yaml
          cat superhero-ui/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Undeploy ${GITHUB_REF_SLUG}.dev.aepps.com"

      - name: Push deploy changes to staging branch
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: aeternity/gitops-apps
          branch: dev
