name: Staging Deploy Test Pipeline

on:
  push:
    branches: 
      - feat/gh-actions-docker-build
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: dev
          fetch-depth: 0

      - uses: rlespinasse/github-slug-action@v3.x

      - run: |
          sudo snap install yq
          yq eval -i '.app.versions += $GITHUB_REF_SLUG_URL' superhero-ui/values.yaml
          yq eval -i '.. style="double"' superhero-ui/values.yaml
          cat superhero-ui/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: aeternity/gitops-apps.git
          branch: dev
