name: Web Pipeline

on:
  push:
    branches: 
      - master
    tags:
      - 'v*'
  pull_request:
    branches: [ master, develop ]
    types: [ opened, closed ]

jobs:
  main:
    runs-on: ubuntu-latest    
    name: Web build docker
    steps:
      - if: github.ref != 'refs/heads/develop'
        uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - if: github.ref != 'refs/heads/develop'
        run: git branch develop origin/develop

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract metadata for docker
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aeternity/superhero-ui-web
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=ref,event=tag
            type=ref,event=pr
      
      - name: Build and push docker image
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: staging
          persist-credentials: false
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Staging deploy
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: aeternity/ae-github-actions/staging-deploy@v1
        with:
          pr-number: $PR_NUMBER
          env: "stg"

      - name: Staging undeploy
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: aeternity/ae-github-actions/staging-undeploy@v1
        with:
          pr-number: $PR_NUMBER
          env: "stg"
