name: Web Pipeline

on:
  push:
    branches: 
      - feat/gh-actions-docker-build
    tags:
      - 'v*'
  pull_request:
    branches: [ feat/gh-actions-docker-build ]

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ format('/home/{0}/superhero-ui', secrets.SSR_STAGE_USER) }}
      
    name: Web Build/Test/Docker
    steps:
      - if: github.ref != 'refs/heads/develop'
        uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - if: github.ref != 'refs/heads/develop'
        run: git branch develop origin/develop

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aeternity/superhero-ui
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.web
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: dev
          path: gitops-apps

      - run: |
          cd gitops-apps
          date > gitops-apps/generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
